name: Homeassistant
control: hidden
entities:
  - sensor.ha_version
  - sensor.newest_ha_version
  - script.restart_homeassistant
  - script.update_homeassistant_config
  - script.update_homeassistant
  - group.alarm_clock_janis