name: Services Frontend
control: hidden
entities:
  - switch.flexget
  - switch.emby
  - switch.ombi
  - switch.grafana
  - switch.find
  - switch.sonarr
  - switch.radarr
  - switch.headphones
  - switch.jackett