# Turn light on, on motion
- alias: motion_light
  trigger:
    - platform: event
      event_type: motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d00010f8100
  condition:
    condition: template
    value_template: '{{ states.group.light_livingroom.state == "off" and states.alarm_control_panel.alarm.state == "disarmed" and (states.sun.sun.state == "below_horizon" or now().hour <= 9) }}'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.livingroom_normal
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.livingroom_motion_timer