- platform: template
  sensors:
    balcony_door_open:
      entity_id: binary_sensor.door_window_sensor_158d000154b7c0
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d000154b7c0', 'on') %}
          on
        {% else %}
          off
        {% endif %}