- alias: Start party mode
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
  action:
    - service: script.party_lights_loop
    - service: shell_command.kodi_start_party

- alias: Stop party mode
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'off'
  action:
    - service: script.party_over
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi_on_firetv