sequence:
  - condition: state
    entity_id: input_boolean.dinner_mode
    state: 'off'
  - condition: state
    entity_id: group.light_livingroom
    state: 'on'
  - condition: template
    value_template: '{{ Player.uuid == states("sensor.emby_player_uuid") }}'
  - delay:
      seconds: 5
  - service: scene.turn_on
    data:
      entity_id: scene.livingroom_normal