entities:
  - name: Flexget
    url: http://192.168.137.49:8003
  - name: Emby
    url: !secret weblink_emby
  - name: Grafana
    url: !secret weblink_grafana
  - name: Mayan EDMS
    url: !secret weblink_mayan
  - name: Owncloud
    url: !secret weblink_owncloud
  - name: Ombi
    url: !secret weblink_ombi
  - name: Find
    url: http://192.168.137.49:8006
  - name: Sonarr
    url: http://192.168.137.49:8002
  - name: Radarr
    url: http://192.168.137.49:8007
  - name: Headphones
    url: http://192.168.137.49:8010/headphones
  - name: Jackett
    url: http://192.168.137.49:8009