host: 192.168.137.49
username: home-assistant
password: !secret influx_pwd
include:
  entities:
    - sensor.transmission_down_speed
    - sensor.transmission_up_speed
    - sensor.owm_temperature
    - sensor.dark_sky_temperature
    - sensor.disk_use_
    - sensor.disk_free_
    - sensor.disk_use_mntshare
    - sensor.disk_free_mntshare
    - sensor.disk_use_mntdisk1
    - sensor.disk_free_mntdisk1
    - sensor.disk_use_mntdisk2
    - sensor.disk_free_mntdisk2
    - sensor.disk_use_mntdisk3
    - sensor.disk_free_mntdisk3
    - sensor.disk_use_mntdisk4
    - sensor.disk_free_mntdisk4
    - sensor.disk_use_mntbackup
    - sensor.disk_free_mntbackup
    - sensor.ram_use
    - sensor.swap_use
    - sensor.cpu_use
    - sensor.cpu_speed
    - sensor.cpu_temperature
    - sensor.disk1_temperature
    - sensor.disk2_temperature
    - sensor.disk3_temperature
    - sensor.disk4_temperature
    - sensor.humidity_158d0001a4a582
    - sensor.pressure_158d0001a4a582
    - sensor.temperature_158d0001a4a582
    - sensor.humidity_158d0001a35e24
    - sensor.pressure_158d0001a35e24
    - sensor.temperature_158d0001a35e24