host: 192.168.137.49
username: home-assistant
password: !secret influx_pwd
include:
  entities:
    - sensor.transmission_down_speed
    - sensor.transmission_up_speed
    - sensor.owm_temperature
    - sensor.disk_use_
    - sensor.disk_free_
    - sensor.disk_use_mntshare
    - sensor.disk_free_mntshare
    - sensor.disk_use_mntext1
    - sensor.disk_free_mntext1
    - sensor.disk_use_mntext2
    - sensor.disk_free_mntext2
    - sensor.disk_use_mntext3
    - sensor.disk_free_mntext3
    - sensor.disk_use_mntbackup
    - sensor.disk_free_mntbackup
    - sensor.received_eth0
    - sensor.sent_eth0
    - sensor.ram_use
    - sensor.ram_free
    - sensor.cpu_use
    - sensor.cpu_speed
    - binary_sensor.motion_sensor_158d00010f8100