- platform: template
  sensors:
    ram:
      entity_id: sensor.ram_use
      friendly_name: "Ram Usage"
      value_template: >
        {{ states("sensor.ram_use") }} MB / {{ ((states("sensor.ram_use")|float) + (states("sensor.ram_free") | float)) | round(2) }} MB

    swap:
      entity_id: sensor.swap_use
      friendly_name: Swap Usage
      value_template: >
        {{ (states("sensor.swap_use") | float * 1000) | int }} MB / {{ (((states("sensor.swap_use") | float) + (states("sensor.swap_free") | float)) * 1000) | int }} MB

    network:
      entity_id:
        - sensor.received_eth0
        - sensor.sent_eth0
      friendly_name: "In / Out"
      value_template: >
        {{ (states("sensor.received_eth0") | float / 1000) | round(2) }} GB / {{ (states("sensor.sent_eth0") | float / 1000) | round(2) }} GB

    nas_disk:
      entity_id: sensor.disk_use_mntshare
      friendly_name: "NAS Usage"
      value_template: >
        {{ (states("sensor.disk_use_mntshare") | float / 1000)  | round(2) }} TB / {{ (((states("sensor.disk_use_mntshare") | float) + (states("sensor.disk_free_mntshare") |float)) / 1000) | round(2) }} TB

    backup_disk:
      entity_id: sensor.disk_use_mntbackup
      friendly_name: "Backup Usage"
      value_template: >
        {{ (states("sensor.disk_use_mntbackup") | float / 1000)  | round(2) }} TB / {{ (((states("sensor.disk_use_mntbackup") | float) + (states("sensor.disk_free_mntbackup") |float)) / 1000) | round(2) }} TB

    uptime:
      entity_id: sensor.since_last_boot
      friendly_name: "Uptime"
      value_template: >
        {{ states.sensor.since_last_boot.state[0:-7] }}