# Turn light on if xiaomi button is clicked long
- alias: xiaomi_liv_hold
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00011033aa
      click_type: hold
  action:
    - service_template: >
        {%- if states.group.light_livingroom.state == "on" -%}
          scene.turn_on
        {%- else -%}
          light.turn_off
        {%- endif -%}
      data_template:
        entity_id: >
          {%- if states.group.light_livingroom.state == "on" -%}
            scene.livingroom_normal
          {%- else -%}
            group.light_livingroom
          {%- endif -%}