name: Misc
entities:
  - sensor.firetv
  - sensor.nas
  - sensor.emulationstation
  - sensor.milightbridge
  - sensor.xiaomi_gateway
  - sensor.broadlinkrmpro
  - sensor.nintendo3ds
  - sensor.janis_fire7
  - sensor.nexus7livingroom
  - sensor.kitchenmpd
  - sensor.guestroommpd
  - sensor.bedroommpd
  - sensor.bathroommpd