- name: Janis
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.janis_handy.attributes.latitude }},{{ states.device_tracker.janis_handy.attributes.longitude }}&zoom=13&size=600x600&maptype=roadmap&markers=color:red%7Clabel:J%7C{{ states.device_tracker.janis_handy.attributes.latitude }},{{ states.device_tracker.janis_handy.attributes.longitude }}
  limit_refetch_to_url_change: true

- name: Lena
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.lena_handy.attributes.latitude }},{{ states.device_tracker.lena_handy.attributes.longitude }}&zoom=13&size=600x600&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.lena_handy.attributes.latitude }},{{ states.device_tracker.lena_handy.attributes.longitude }}
  limit_refetch_to_url_change: true

- name: fire_living_room
  platform: mjpg
  still_image_url: http://192.168.137.55:8080/video
  limit_refetch_to_url_change: true
